spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mawa?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: use-your-own-password(from MySQL Workbench)
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

server:
  port: 8080